server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: kafka-search
  kafka:
    streams:
      bootstrap-servers: ${KAFKA_HOST:localhost:9092,localhost:9093,localhost:9094}
      application-id: ${APPLICATION_ID:payment-stream-app}
    consumer:
      properties:
        "[spring.json.trusted.packages]": "*"

app:
  topic:
    input: ${TOPIC:payments}

logging:
  level:
    "[org.springframework.kafka]": DEBUG
    "[org.apache.kafka]": INFO